#!/usr/bin/env bash

# Script to make plots
# This needs to be called from $CMSSW_BASE/src/CMGTools/TTHAnalysis/python/plotter

lumi=36.5

mca=susy-1lep/mca/mca-Spring16_All_sllSF_Moriond17.txt
cuts=susy-1lep/1l_basicCutsFullCutFlow.txt
trees=/eos/uscms/store/user/bschneid/analysis/2016-12-12_cmgTuples_spring16_1lep_HT350_LT150/
friends=/eos/uscms/store/user/bschneid/analysis/2016-12-12_cmgTuples_spring16_1lep_HT350_LT150/friends_v3/evVarFriend_{cname}.root

# QCD estimation, define QCD as signal
python mcPlots.py \
    "${mca}" \
    "${cuts}" \
    susy-1lep/plots/base_plots.txt \
    -P "${trees}" \
    -F sf/t "${friends}" \
    -l "${lumi}" \
    -j $(nproc) \
    --s2v \
    --tree treeProducerSusySingleLepton \
    -G \
    -f \
    --showRatio \
    --maxRatioRange 0.05 1.95 \
    --fixRatioRange \
    --noErrorBandOnRatio \
    --noStackSig \
    --showIndivSigs \
    --scaleBkgToData TTsemiLep \
    --scaleBkgToData TTdiLep \
    --scaleBkgToData TTV \
    --scaleBkgToData SingleT \
    --scaleBkgToData WJets \
    --scaleBkgToData DY \
    --scaleBkgToData VV \
    --scaleBkgToData QCD \
    --showSF

## Fit QCD estimation to data in anti-selected region; this is only useful for
## plotting; define QCD as background
#python mcPlots.py \
#    "${mca}" \
#    susy-1lep/mca/mycuts.txt \
#    susy-1lep/mca/myplots.txt \
#    -P "${trees}" \
#    -F sf/t "${friends}" \
#    -l "${lumi}" \
#    -j $(nproc) \
#    --s2v \
#    --tree treeProducerSusySingleLepton \
#    -G \
#    -f \
#    --noStackSig \
#    --showIndivSigs \
#    --showRatio \
#    --maxRatioRange 0.0 2.0 \
#    --fixRatioRange \
#    --noErrorBandOnRatio \
#    --scaleBkgToData QCD \
#    --showSF

